x-api: &api
  image: zanfranceschi/rinha-de-backend-2026-zan-dotnet:202605030438
  volumes:
    - sock:/run/sock
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "160M"

services:
  api1:
    <<: *api
    environment:
      SOCKET_PATH: /run/sock/api1.sock
      NPROBE: 1
      NPROBE_RETRY_EXTRA: 75
      KNN_K: 5
      INSTRUMENTED: false
      Logging__LogLevel__Default: None

  api2:
    <<: *api
    environment:
      SOCKET_PATH: /run/sock/api2.sock
      NPROBE: 1
      NPROBE_RETRY_EXTRA: 75
      KNN_K: 5
      INSTRUMENTED: false
      Logging__LogLevel__Default: None

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - sock:/run/sock
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30M"

volumes:
  sock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
