x-api: &api
  image: zanfranceschi/rinha-de-backend-2026-zan-dotnet:latest
  environment:
    ASPNETCORE_URLS: "http://+:3000"
    X: 1
  expose:
    - "3000"
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "160M"

services:
  api1:
    <<: *api

  api2:
    <<: *api

  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30M"
